### PR TITLE
Adds keywords to package.json

### LINKED ISSUE #19: Re-add keywords to package.json
```json
"keywords": [
    "youtube",
    "download",
    "cli",
    "ffmpeg",
    "encode"
  ],
```

### PR DESCRIPTION
**Pull request by nfiles**
Resolves #19 

Adds the specified keywords to the `package.json`. Let me know if I missed anything. I have not added keywords to a package before. :)

### CODE REVIEW

**Comment by JimmyBoh** [comment]
Nice, did you [register for Hacktoberfest first](https://hacktoberfest.digitalocean.com/)?

Looks like the download of ffmpeg is failing on the build server!

**Comment by nfiles** [comment]
I did! :)

Huh, that's strange. I don't think `flvtool2` exists in `apt-get` anymore. I'm running Ubuntu 14.04 (yikes, I should upgrade). It looks like the `fluent-ffmpeg` Travis CI build is failing as well: https://travis-ci.org/fluent-ffmpeg/node-fluent-ffmpeg/jobs/286271956

**Comment by nfiles** [comment]
I added a third-party repository for installing `flvtool2`, which seems to fix the CI build. :)

**Comment by JimmyBoh** [comment]
Awesome!

**Pull request merged**
